# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0145962c1ffad874752e081d8cf4a2488aaeac761b04702957c284864eab76ade84076013f88a85d46e66bbc1f52d875a51ed111e1aee3190c1f899dbf26f931

test:
  secret_key_base: 25323583c0d308231ca9785b1e10ac6c66ab4f7a937ea365f5c952a9b7fd215eff997d07eb76dac2c0633ece64d91d1b383ef6fd84e96d7c0c65553f1c029937

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
